music_directory    "~/Music"
playlist_directory "~/.local/share/mpd/playlists"
db_file            "~/.local/share/mpd/database"
state_file         "~/.local/share/mpd/state"
sticker_file       "~/.local/share/mpd/sticker.sql"
log_file           "syslog"

bind_to_address "127.0.0.1"
port            "6600"

auto_update "yes"

audio_output {
    type "pipewire"
    name "PipeWire Output"
}

# Visualization data for ncmpcpp
audio_output {
    type   "fifo"
    name   "Visualizer"
    path   "/tmp/mpd.fifo"
    format "44100:16:2"
}
